# Generated by Django 4.0.3 on 2022-04-05 10:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('translation_en', models.CharField(max_length=50)),
                ('number_of_Ayah', models.CharField(max_length=50)),
                ('audio', models.CharField(max_length=50)),
                ('desc', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Surai',
                'verbose_name_plural': 'Surai',
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', ckeditor.fields.RichTextField()),
                ('text_en', ckeditor.fields.RichTextField()),
                ('experiences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.surai')),
            ],
            options={
                'verbose_name': 'Ayah',
                'verbose_name_plural': 'Ayah',
            },
        ),
    ]
