# Generated by Django 4.0.3 on 2022-04-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayah',
            name='audio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
