# Generated by Django 4.0.3 on 2022-04-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ayah_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='surai',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
