# Generated by Django 4.0.3 on 2022-04-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ayah_chapter_ayah_verse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ayah',
            old_name='text_en',
            new_name='text_uz',
        ),
    ]
