# Generated by Django 4.0.3 on 2022-04-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_text_en_ayah_text_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='surai',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
