# Generated by Django 4.0.3 on 2022-04-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_surai_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayah',
            name='verse_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ayah',
            name='audio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surai',
            name='audio',
            field=models.CharField(max_length=200),
        ),
    ]
