# Generated by Django 4.1.5 on 2023-01-28 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_ayah_verse_ar_alter_ayah_audio_alter_surai_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('poster', models.ImageField(default='posters/default.png', upload_to='posters', verbose_name='Poster')),
                ('code', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('utype', models.BooleanField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
