# Generated by Django 4.1.5 on 2023-01-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
    ]
