# Generated by Django 4.1.4 on 2023-01-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_application_is_it_for_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
