# Generated by Django 4.1.4 on 2023-01-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_application_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payed',
            field=models.IntegerField(default=0),
        ),
    ]
