# Generated by Django 4.1.4 on 2023-01-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_application_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='_cash',
            field=models.IntegerField(default=0),
        ),
    ]
