# Generated by Django 4.1.4 on 2023-01-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_application__cash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='_cash',
            new_name='ca_sh',
        ),
    ]
