# Generated by Django 4.1.4 on 2023-01-29 05:16

import ckeditor.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename__cash_application_ca_sh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jamgarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', ckeditor.fields.RichTextField()),
                ('needed_cash', models.IntegerField()),
                ('payed', models.IntegerField()),
                ('remain', models.IntegerField()),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to=main.models.jami)),
            ],
        ),
    ]
