# Generated by Django 4.1.4 on 2023-01-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_jamgarma'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
